<?php
/**
 * @package                                     NXD Football Manager 2 Players Module (mod_nxdfm2_players)
 *
 * @author                                      NXD | Marco Rensch <support@nx-designs.ch>
 * @copyright                                   Copyright(R) 2024 by NXD nx-designs
 * @license                                     GNU General Public License version 2 or later; see LICENSE.txt
 * @link                                        https://www.nx-designs.ch
 *
 */

namespace NXD\Module\FootballManagerPlayers\Site\Field;

defined('_JEXEC') or die;

use Joomla\CMS\Factory;
use Joomla\CMS\Form\Field\HiddenField;
use Joomla\CMS\Form\FormField;

class CustomModuleCodeField extends HiddenField
{
	protected $type = 'CustomModuleCode';
	protected function getLabel()
	{
		return parent::getLabel(); // TODO: Change the autogenerated stub
	}

	protected function getInput(): string
	{
		$this->addStylesheet();
		return parent::getInput(); // TODO: Change the autogenerated stub
	}

	private function addStylesheet()
	{
		$wa = Factory::getApplication()->getDocument()->getWebAssetManager();
		$wa->registerAndUseScript('CustomBackendJs', 'modules/mod_nxdfm2_players/src/Field/assets/js/CustomModuleCode.js');
		$wa->registerAndUseStyle('CustomBackendCss', 'modules/mod_nxdfm2_players/src/Field/assets/css/CustomModuleCode.css');
	}

}