<?php

namespace NXD\Module\FootballManagerPlayers\Site\Field;

use Joomla\CMS\Factory;
use Joomla\CMS\Form\Field\HiddenField;
use Joomla\CMS\Form\FormField;

class CustomModuleCodeField extends HiddenField
{
	protected $type = 'CustomModuleCode';
	protected function getLabel()
	{
		return parent::getLabel(); // TODO: Change the autogenerated stub
	}

	protected function getInput(): string
	{
		$this->addStylesheet();
		return parent::getInput(); // TODO: Change the autogenerated stub
	}

	private function addStylesheet()
	{
		$wa = Factory::getApplication()->getDocument()->getWebAssetManager();
		$wa->registerAndUseStyle('CustomBackendCss', 'modules/mod_nxdfm2_players/src/Field/assets/css/CustomModuleCode.css');
	}

}